### ISSUE TITLE
It requires Hydrogen version v1.0.0 to run

### ISSUE THREAD

**Issue by libranxz** [nikitakit/hydrogen-auth#1]
Please refer  the last comment on nteract/hydrogen#497

**Comment by nikitakit** [comment]
You can remove the check on this line: https://github.com/nikitakit/hydrogen-auth/blob/master/lib/main.js#L166 (just delete the if statement and what's inside it) and make sure to activate the hydrogen package _before_ running the auth commands.

It doesn't actually need a recent hydrogen version, it just checks that the hydrogen package has been activated first.

Alternatively, you can run hydrogen from github (it will pass the version check)

**Comment by libranxz** [comment]
Thanks @nikitakit 
I think I broke the Hydrogen package on my mac.
I tired to uninstall my current hydrogen package and install it through github. Below is what I did.

```
rm -R ~/.atom/packages/Hydrogen
git clone ....(hydrogen repo from github)
cd hydrogen
npm install
```

Then I got that version installed, but I cannot do any setting, the setting place is empty. So I uninstall it from atom settings panel then tried to install it again by using `apm install hydrogen`
I got it installed. However, this time it's not working... When I do "Hydrogen: Connect to Remote Kernel", there is no response (it use to let me select gateway and session). What is really wired is that every time after I run a Hydrogen command, then I cannot find any Hydrogen command in command palette.

It worked well before. Do you have any thought it?  I really need to fix it for my work. Thanks ahead!!

**Comment by nikitakit** [comment]
Maybe try `PYTHON=python2.7 apm install` inside the folder where hydrogen is?

I remember having the same issue, but no what I did to fix it. It's definitely an installation issue though, not a problem with the source code itself.

**Comment by libranxz** [comment]
you meant still clone the github version then run `PYTHON=python2.7 am install`?

**Comment by nikitakit** [comment]
Yes, to try installing the github version with `apm install` (that was a typo from me: should be apm, not am)

**Comment by libranxz** [comment]
I did that then the setting page for Hydrogen looks like below. No place for me to do any setting.
![image](https://cloud.githubusercontent.com/assets/8029913/20272103/e74180fa-aa5a-11e6-8cfb-cc5a4059a974.png)

**Comment by nikitakit** [comment]
Uhh I forget what fixes this. Try deleting the install folder (should be something like `~/.atom/packages/Hydrogen`) and the node_modules folder inside your repo clone. Then try installing again.

Sorry, I had the exact same issue before, but I forget exactly what I tried before I managed to perturb it away.

**Comment by libranxz** [comment]
What is the node_modules folder? I don't see any folder named as that my repo clone. Below is what I have.
![image](https://cloud.githubusercontent.com/assets/8029913/20272511/176bc74e-aa5c-11e6-8749-42ef9dd9d7fe.png)

**Comment by nikitakit** [comment]
Oh then you can disregard that instruction. (As a plug in author, I use a slightly different install method that has it show up.)

Sorry for brevity, I'm on phone for now

**Comment by libranxz** [comment]
Np. I reinstall the atom and now the Hydrogen is working. Now let's come back the this auth plugin package. You mentioned that I need to activate hydrogen package before run it. How should I activate it? I tried to run a random hydrogen command and then run this plugin. It didn't work out.

**Comment by nikitakit** [comment]
Running a hydrogen command should be enough to activate the hydrogen package.

The issue is probably that in addition to having hydrogen active, you also need to sort out the version incompatibility. You can do that by installing hydrogen from github (a newer version of hydrogen), or by making the hydrogen-auth change I suggested in my first comment (this removes a version check from hydrogen-auth).

**Comment by libranxz** [comment]
I commented the version check and now I can run it. However, I got another issue. My remote notebook link is something like `https://xxxxx:8888`. Since the the package only support `http`, not `https`, I used `http` in the gateway setup. Then I run the auth plugin, selected gateway and typed in password. Then I got a green message asking me to connect the remote kernel. When I connected with the kernel, I got a message says 'connection to gateway failed'.

**Comment by nikitakit** [comment]
Why do you say that the package doesn't support `https`? That was certainly never the intent, so you should let me know what breaks for using `https` correctly. (Specifying the wrong URL in the config is never going to give correct results)

**Comment by libranxz** [comment]
This is the error I got if I use https in the gateway setup then run the auth login.
![image](https://cloud.githubusercontent.com/assets/8029913/20291398/ecd440e4-aab3-11e6-8741-41026208ec8b.png)

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.12.0
**Electron Version**: 1.3.6
**System**: Mac OS X 10.11.6
**Thrown From**: [hydrogen-auth](https://github.com/nikitakit/hydrogen-auth) package, v0.0.1

### Stack Trace

Uncaught Error: Protocol "https:" not supported. Expected "http:"

```
At _http_client.js:55

Error: Protocol "https:" not supported. Expected "http:"
  at new ClientRequest (_http_client.js:55:11)
  at Object.exports.request (http.js:31:10)
  at connect (/Users/markzhou/.atom/packages/hydrogen-auth/lib/main.js:70:24)
  at TextInputView.onConfirmed (/Users/markzhou/.atom/packages/hydrogen-auth/lib/main.js:36:17)
  at TextInputView.confirm (/Users/markzhou/.atom/packages/hydrogen-auth/lib/views.coffee:58:10)
  at space-pen-div.<anonymous> (/Users/markzhou/.atom/packages/hydrogen-auth/lib/views.coffee:5:59)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:584:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:379:22)
  at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)

```

### Commands

```
     -9:46.9.0 command-palette:toggle (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
  2x -9:44.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -9:39 hydrogen-auth:login-to-gateway (atom-text-editor.editor.enable-nuclide-find-references)
  2x -9:34.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -9:23.8.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  5x -9:20.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -9:11.3.0 command-palette:toggle (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
     -9:06.4.0 hydrogen:connect-to-remote-kernel (atom-text-editor.editor.enable-nuclide-find-references)
  2x -0:26.4.0 hydrogen-auth:login-to-gateway (div.package-detail.panels-item)
  2x -0:08.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

``` json
{
  "core": {
    "automaticallyUpdate": false,
    "customFileTypes": {
      "source.cpp": [
        "h"
      ],
      "source.ini": [
        ".buckconfig",
        ".hgrc"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "TARGETS",
        "cconf",
        "cinc",
        "ctw",
        "mcconf",
        "tw",
        "thrift-cvalidator",
        "BUCK"
      ]
    },
    "disabledPackages": [
      "metrics",
      "fuzzy-finder",
      "tree-view"
    ],
    "telemetryConsent": "no"
  }
}
```

### Installed Packages

``` coffee
# User
haskell-grammar, v0.4.0 (active)
highlight-selected, v0.11.2 (active)
Hydrogen, v0.15.0 (active)
hydrogen-auth, v0.0.1 (active)
language-babel, v2.47.0 (active)
language-ini, v1.16.0 (active)
language-ocaml, v1.1.2 (active)
language-swift, v0.5.0 (active)
language-thrift, v1.0.2 (active)
merge-conflicts, v1.4.4 (active)
nuclide, v0.181.43492191 (active)
nuclide-format-js, v0.0.36 (inactive)
sort-lines, v0.14.0 (inactive)
tool-bar, v1.0.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.0 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.1 (inactive)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.3 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (inactive)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by nikitakit** [comment]
@xinzhou1023 Sorry about that. I didn't expect this to be a problem.

I'm not able to test a fix at the moment, but if you have some time you might want to try the (untested) new commit I just pushed. Thanks for pointing out the https issue, I'll be sure to address it.

**Comment by libranxz** [comment]
Thanks for the quick fix, @nikitakit . I tried the new commit and it let me pass through the auth setup and I got the green message asking me to connect to remote. Then it failed in the next step. I got the same error, 'Connect to gateway failed'. Please let me know when you make new commit, would love to test it.

**Comment by nikitakit** [comment]
@xinzhou1023 I just double-checked that connecting to https server works correctly as of the current commit.

By any chance, is your server using a self-signed certificate? If so, you need to fix your security setup. The preferred solution would be to use Let's Encrypt to issue a certificate. To test if things will work barring security concerns, you can start atom using the `NODE_TLS_REJECT_UNAUTHORIZED=0 atom .` command. Note that this disables security checks throughout atom, and therefore opens you up to security attacks and cannot be a permanent solution to the problem.

**Comment by libranxz** [comment]
@nikitakit  The notebook config is setup by my company and I'm not familiar to it. I think it's self-signed certificate since I don't need login every time. Below is my notebook config file. I think that may help.
![image](https://cloud.githubusercontent.com/assets/8029913/20361592/284f0d0e-ac06-11e6-9ac4-f0ddb362e12f.png)

**Comment by nikitakit** [comment]
Can you try the security-disabled setting above once, and see if it makes things work?

**Comment by xinzhou1023** [comment]
By security-disabled setting, do you mean comment out line 7 and 8?

**Comment by libranxz** [comment]
OK, I commented out line 7 and 8 in the setup above, now I can use Hydrogen to connect to my notebook. It works well since the link becomes `http`, not `https`. No need to use auth plugin.

Now the problem is that is there a way to make it work if the security setting is enable?

**Comment by nikitakit** [comment]
No I meant `NODE_TLS_REJECT_UNAUTHORIZED=0 atom`. Sorry, on phone again

**Comment by libranxz** [comment]
Np. By doing that, it works! So is there a solution to fix it if I want to run atom in a normal way?

**Comment by nikitakit** [comment]
The issue of using untrusted certificates is outside my control, so I don't think I'm going to address this further. A big part of the problem lies with nodejs itself. The nodejs developrs seem to be working on a patch to support using the system certificate store (though it may take months to a year for it to actually be released).

If you want to just get things working for yourself, you can modify the source code of this package to work for your usecase. You will need to transfer the certfile (`.pem` extension) to the machine that has atom installed, and figure out some way for node to accept it as a trusted certificate.

I've attached some refs below to get you started, if you want to go down that path. However I currently can't provide further support beyond that.

Refs:
- https://www.npmjs.com/package/ssl-root-cas#addfilefilepath
- https://github.com/nikitakit/hydrogen-auth/blob/master/lib/main.js#L74
- http://stackoverflow.com/questions/21004645/where-is-nodes-certificate-store
- https://nodejs.org/api/https.html#https_https_request_options_callback

**Comment by libranxz** [comment]
Thanks, @nikitakit . I'll take a look and close this issue. Thanks again for building this plugin.
